### ISSUE TITLE
question about parFinder

### ISSUE THREAD

**Issue by D0N-B0T** [cooltheo17/BinanceBot#2]
----------------------------------
|            - BTC -             |
+--------------------------------+
|      Alpha profit: 0.57 $      |
+--------------------------------+
|  Simple MACD profit: -0.16 $   |
+--------------------------------+
|  Complex MACD profit: 1.07 $   |
+--------------------------------+
|        Stop Limit: -4 %        |
+--------------------------------+
how should i interpretate this? balance in parfinder.py is 100 so  should i add every profit to final balance? 0.57+-0.16+1.07=101,48?

**Comment by cooltheo17** [comment]
So Alpha profit is the profit someone would make if they put 100$ in bitcoin exactly 10 days ago and sold now. Simple MACD is the profit someone would make if they bought and sold accordingly at each intersection. Lastly Complex MACD is the profit someone would make if they used the same strategie but with a stop loss at the percentage below. In conclusion no don't add then. Each one is a different strategie. The aim of the tool is for you to decide which coin follows the MACD index the best. You can email me any further questions. Thank you.
